name: Run Telegram Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # รันทุก 5 นาที (จำเป็นเพราะ GitHub Actions ไม่ support long-running jobs)
  workflow_dispatch:     # ให้เรียกใช้ manual ได้

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Write credentials.json
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          python main.py